export { default as Navbar } from "./Navbar/Navbar"
export {default as Home } from "./Home/Home"
export {default as Updates} from "./Updates/Updates"
export {default as Deals} from "./Deals/Deals"
export {default as Compete} from "./Compete/Compete"